# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: "agile-app.yaml"
      - id: check-json
      # - id: check-added-large-files
      - id: requirements-txt-fixer
      - id: check-ast # Validate python
  - repo: https://github.com/hadialqattan/pycln
    rev: v2.5.0
    hooks:
      - id: pycln # Remove unused imports
        args: ["--all"]
        exclude: "__init__.py"
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black", "--filter-files"]
  - repo: https://github.com/psf/black
    rev: 21.10b0
    hooks:
      - id: black # Python code auto formatter
        additional_dependencies: ["click==8.0.4"]
        exclude: "__init__.py"
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: pipenv run pytest
        language: system
        pass_filenames: false
        always_run: true
        args: ["--verbosity=1"]
  - repo: local
    hooks:
      - id: restricted-filenames
        name: Check commits for unexpected file extensions
        entry: These file extensions are unusual and should be checked
        language: fail
        files: '.*\.(xlsx|doc|tif|png|npz|jpg|jpeg|gif)'
      # - id: restricted-file-types
      #   name: Check commits for unexpected file types
      #   entry: These file types are unusual and should be checked
      #   language: fail
      #   types: ["binary"]
      #   exclude_types: ["image"]
  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: pipenv run pylint
        language: system
        types: [python]
        require_serial: true
        exclude: ^(manage\.py|config/.*|.*/migrations/.*|.*/tests/.*)$
        args: [
            "--rcfile=.pylintrc", # Usar arquivo de configuração .pylintrc
            "-rn", # Only display messages
            "-sn", # Don't display the score
          ]
